import java.util.Scanner;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class IntToByte {
	 public String convertIntToByte(Integer num) {
	        return Integer.toBinaryString(num);
	    }

	    public Integer askUserForInt() {
	    	Scanner in= new Scanner(System.in);
	    	System.out.println("Input Integer");
			return in.nextInt();
					
	    }
	    public static void main(String[] args) {
	    	IntToByte hello = new IntToByte();
	        System.out.println(hello.convertIntToByte(hello.askUserForInt()));
	    }
}
