/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.testng.annotations.*;
import static org.testng.Assert.*;

import java.io.ByteArrayInputStream;

public class AppTest {
	
	@Test public void appHasAGreeting() {
		IntToByte classUnderTest = new IntToByte();
        assertEquals(classUnderTest.convertIntToByte(123), "1111011", "app should return byte value");        
	}
	
	@Test public void askUser(){
		System.setIn(new ByteArrayInputStream("123".getBytes()));
		IntToByte classUnderTest = new IntToByte();
		Integer input = classUnderTest.askUserForInt();
		String intToByte = classUnderTest.convertIntToByte(input);
		assertEquals(intToByte, "1111011", "Input is correct");
	}
}
